Fix added departmentcreate to create action
Tools4everBV/Hello-Conn-Prov-Target-Zermelo pull request #6
Opened 2024-12-16 12:46 UTC by JeroenBL

departmentOfBranch onderdeel gemaakt van de create. Is optioneel en wordt alleen uitgevoerd als in de fieldMapping de velden: classRoom en schoolName een waarde hebben.

2025-01-13 12:22 UTC, rhouthuijzen requested changes
Structuur ziet er goed uit. Lijkt op dat er nog een klein foutje in zit m.b.t. 'actielijst'. Mogelijk kunnen we de dryrun message nog iets finetunen.

2025-01-13 12:22 UTC, rhouthuijzen commented on create.ps1
> +        foreach ($action in $orderedActions){
Ik had hier eigenlijk $action in $actions verwacht. $actions wordt wel gevuld maar nergens aangeroepen. Zie ook update script

2025-01-13 12:22 UTC, rhouthuijzen commented on create.ps1
> +        $orderedActions += 'Update-DepartmentOfBranch'
Is dit nog nodig als je $actions gaat gebruiken. Dan vul je dit al op regel 278

2025-01-13 12:22 UTC, rhouthuijzen commented on create.ps1
>          Write-Information "[DryRun] $action Zermelo account for: [$($personContext.Person.DisplayName)], will be executed during enforcement" -Verbose
Als de dryRun hier wordt afgevangen zou ik graag wel de actielijst ($actions?) willen zien. Zodat je in iedergeval weet welke acties HelloID allemaal zou uitvoeren.

2025-01-13 12:22 UTC, rhouthuijzen commented on create.ps1
> +    if (-not [string]::IsNullOrEmpty($actionContext.Data.schoolName) -and
Mogelijk hiervoor nog informatie toevoegen in de readme als remark (zie ik nu geen commit op).

schoolName en classRoom

Of in de description van de fieldmapping

2025-01-13 12:22 UTC, rhouthuijzen commented on update.ps1
Onder Regel 350 zou ik hier ook een lijst van actions verwachten in $actions. Uit de dryrun kan je bijvoorbeeld niet halen of Regel 337 of 345 is toegevoegd aan $actions

2025-01-31 08:29 UTC, JeroenBL commented on create.ps1
> +        foreach ($action in $orderedActions){
Wordt aangeroepen op regel: `323`.
```powershell
    $orderedActions = @($actions | Where-Object { $_ -notin @('Update-DepartmentOfBranch') })
    if ($actions -contains 'Update-DepartmentOfBranch') {
        $orderedActions += 'Update-DepartmentOfBranch'
    }
```

2025-01-31 08:31 UTC, JeroenBL commented on create.ps1
> +        $orderedActions += 'Update-DepartmentOfBranch'
Eigenlijk wel. Ik bouw eerst de lijst van `$actions` op. Daarna ga ik ze nog een keer 'sorteren' zodat de 'Update-DepartmentOfBranch' altijd als laatste wordt uitgevoerd.

2025-01-31 08:31 UTC, JeroenBL commented on create.ps1
>          Write-Information "[DryRun] $action Zermelo account for: [$($personContext.Person.DisplayName)], will be executed during enforcement" -Verbose
Check! Goeie toevoeging.

2025-01-31 08:37 UTC, JeroenBL commented on create.ps1
>          Write-Information "[DryRun] $action Zermelo account for: [$($personContext.Person.DisplayName)], will be executed during enforcement" -Verbose
Ordering en dryRun even omgedraaid zodat de actions ook tijdens dryRun worden weergegeven.

2025-01-31 08:45 UTC, JeroenBL commented on create.ps1
> +    if (-not [string]::IsNullOrEmpty($actionContext.Data.schoolName) -and
Staat al beschreven in de README.

2025-01-31 08:52 UTC, JeroenBL commented on update.ps1
Check. Ook even als informational message teruggegeven.

2025-01-31 08:53 UTC, merged